[sh] change hardtab to softtab

diff --git a/zsh/rc/zshrc b/zsh/rc/zshrc
--- a/zsh/rc/zshrc
+++ b/zsh/rc/zshrc
@@ -1,30 +1,30 @@
-#								,______________________,
-#								|****;/''		/*********/
-#								|**7'			 /*********/
-#								|;(				/*********/
-#												/'********/'
-#											 /*********/
-#										 /'********/'
-#										/*********/				_.
-#									/'********/'			 )*|
-#								 /*********/			 ,7**|
-#								/*********/______/*****|
-#								""""""""""""""""""""""""
-#								__							_
-#								\ \			 ___ __| |_
-#								 > >		|_ /(_-< ' \
-#								/_/			/__|___/_||_|			___
-#																				 |___|
+#               ,______________________,
+#               |****;/''   /*********/
+#               |**7'      /*********/
+#               |;(       /*********/
+#                       /'********/'
+#                      /*********/
+#                    /'********/'
+#                   /*********/       _.
+#                 /'********/'       )*|
+#                /*********/       ,7**|
+#               /*********/______/*****|
+#               """"""""""""""""""""""""
+#               __              _
+#               \ \      ___ __| |_
+#                > >    |_ /(_-< ' \
+#               /_/     /__|___/_||_|     ___
+#                                        |___|
 
-#				* auther		: k0k1
-#				* ver				: 3.40
-
-
+#       * auther    : k0k1
+#       * ver       : 3.40
 
 
 
-# * »		[1] general
-# -------------------------------------------														 /
+
+
+# * »   [1] general
+# -------------------------------------------                            /
 # ----------------------------------------------------------------------/
 # [
 
@@ -46,21 +46,21 @@ alias history='history -E'
 
 # ref. https://rcmdnk.com/blog/2017/10/13/computer-bash-zsh
 function source_file {
-	if [ $# -lt 1 ];then
-		echo "ERROR!!! source_file is called w/o an argument"
-		return
-	fi
-	arg="$1"
-	shift
-	if [ -r "$arg" ]; then
-		. "$arg"
-	fi
+  if [ $# -lt 1 ];then
+    echo "ERROR!!! source_file is called w/o an argument"
+    return
+  fi
+  arg="$1"
+  shift
+  if [ -r "$arg" ]; then
+    . "$arg"
+  fi
 }
 # end
 
 
 
-# * »»	complement -------------------------------------/
+# * »»  complement -------------------------------------/
 # [[
 
 zmodload zsh/mapfile
@@ -82,7 +82,7 @@ fpath=($ZDOTDIR/rc/completion $fpath)
 
 
 
-# * »»	history ----------------------------------------/
+# * »»  history ----------------------------------------/
 # [[
 
 HISTFILE=$HOME/.zsh_history
@@ -105,19 +105,19 @@ function history-all { history -E 1 }
 
 
 
-# * »»	path -------------------------------------------/
+# * »»  path -------------------------------------------/
 # [[
 
 if (( $+commands[go] )); then
-	if [ -e $HOME/.go ]; then
-		export GOPATH=$HOME/.go
-		export PATH=$GOPATH/bin:$PATH
-		export GO15VENDOREXPERIMENT=1
-	fi
+  if [ -e $HOME/.go ]; then
+    export GOPATH=$HOME/.go
+    export PATH=$GOPATH/bin:$PATH
+    export GO15VENDOREXPERIMENT=1
+  fi
 fi
 
 if [ -e $HOME/.cargo/bin ]; then
-	export PATH="$HOME/.cargo/bin:$PATH"
+  export PATH="$HOME/.cargo/bin:$PATH"
 fi
 
 # ]]
@@ -125,35 +125,35 @@ fi
 
 
 
-# * »»	plugin -----------------------------------------/
+# * »»  plugin -----------------------------------------/
 # [[
 
 if (( $+commands[git] )); then
-	# task: make plugin manager
+  # task: make plugin manager
 fi
 
 #https://github.com/junegunn/fzf
 source_file $HOME/.fzf.zsh
 if (( $+commands[fzf] )); then
-	fe() {
-		local file
-		file=$(fzf --query="$1" --select-1 --exit-0)
-		[ -n "$file" ] && ${EDITOR:-vim} "$file"
-	}
+  fe() {
+    local file
+    file=$(fzf --query="$1" --select-1 --exit-0)
+    [ -n "$file" ] && ${EDITOR:-vim} "$file"
+  }
 
-	fd() {
-		local dir
-		dir=$(find ${1:-*} -path '*/\.*' -prune -o -type d -print 2> /dev/null | fzf +m) &&
-		cd "$dir"
-	}
+  fd() {
+    local dir
+    dir=$(find ${1:-*} -path '*/\.*' -prune -o -type d -print 2> /dev/null | fzf +m) &&
+    cd "$dir"
+  }
 
-	fh() {
-		eval $(([ -n "$ZSH_NAME" ] && fc -l 1 || history) | fzf +s | sed 's/ *[0-9]* *//')
-	}
+  fh() {
+    eval $(([ -n "$ZSH_NAME" ] && fc -l 1 || history) | fzf +s | sed 's/ *[0-9]* *//')
+  }
 
-	fkill() {
-		ps -ef | sed 1d | fzf -m | awk '{print $2}' | xargs kill -${1:-9}
-	}
+  fkill() {
+    ps -ef | sed 1d | fzf -m | awk '{print $2}' | xargs kill -${1:-9}
+  }
 fi
 
 source_file ${HOME}/.enhancd/init.sh
@@ -163,7 +163,7 @@ source_file ${HOME}/.enhancd/init.sh
 
 
 
-# * »»	alias -------------------------------------------/
+# * »»  alias -------------------------------------------/
 # [[
 
 alias v='vim'
@@ -172,20 +172,20 @@ function runcpp () { g++ $1 && shift && ./a.out $@ }
 alias -s {c,cpp}=runcpp
 
 function extract() {
-	case $1 in
-		*.tar.gz|*.tgz) tar xzvf $1;;
-		*.tar.xz) tar Jxvf $1;;
-		*.zip) unzip $1;;
-		*.lzh) lha e $1;;
-		*.tar.bz2|*.tbz) tar xjvf $1;;
-		*.tar.Z) tar zxvf $1;;
-		*.gz) gzip -d $1;;
-		*.bz2) bzip2 -dc $1;;
-		*.Z) uncompress $1;;
-		*.tar) tar xvf $1;;
-		*.arj) unarj $1;;
-		*.rar) unrar $1;;
-	esac
+  case $1 in
+    *.tar.gz|*.tgz) tar xzvf $1;;
+    *.tar.xz) tar Jxvf $1;;
+    *.zip) unzip $1;;
+    *.lzh) lha e $1;;
+    *.tar.bz2|*.tbz) tar xjvf $1;;
+    *.tar.Z) tar zxvf $1;;
+    *.gz) gzip -d $1;;
+    *.bz2) bzip2 -dc $1;;
+    *.Z) uncompress $1;;
+    *.tar) tar xvf $1;;
+    *.arj) unarj $1;;
+    *.rar) unrar $1;;
+  esac
 }
 alias -s {gz,tgz,zip,lzh,bz2,tbz,Z,tar,arj,xz,rar}=extract
 
@@ -195,42 +195,42 @@ alias fuck='eval $(thefuck $(fc -ln -1))'
 alias diff='diff -u'
 
 if (( $+commands[tmux] )); then
-	alias tl='tmux ls'
-	alias tk='tmux kill-session -t $1'
-	alias ta='tmux a'
-	alias tat='tmux a -t $1'
+  alias tl='tmux ls'
+  alias tk='tmux kill-session -t $1'
+  alias ta='tmux a'
+  alias tat='tmux a -t $1'
 fi
 
 # * »»» color --------------------------/
 
 # * »»»» cat
 if (( $+commands[pygmentize] )); then
-	alias cat='pygmentize -O style=monokai -f console256 -g'
+  alias cat='pygmentize -O style=monokai -f console256 -g'
 fi
 
 # * »»»» diff
 if (( $+commands[colordiff] )); then
-	alias diff='colordiff -u'
+  alias diff='colordiff -u'
 fi
 
 # * »»»» less
 export MANPAGER='less -R'
 function man() {
-	env \
-		LESS_TERMCAP_mb=$(printf "\e[1;31m") \
-		LESS_TERMCAP_md=$(printf "\e[1;31m") \
-		LESS_TERMCAP_me=$(printf "\e[0m") \
-		LESS_TERMCAP_se=$(printf "\e[0m") \
-		LESS_TERMCAP_so=$(printf "\e[1;44;33m") \
-		LESS_TERMCAP_ue=$(printf "\e[0m") \
-		LESS_TERMCAP_us=$(printf "\e[1;32m") \
-		man "$@"
+  env \
+    LESS_TERMCAP_mb=$(printf "\e[1;31m") \
+    LESS_TERMCAP_md=$(printf "\e[1;31m") \
+    LESS_TERMCAP_me=$(printf "\e[0m") \
+    LESS_TERMCAP_se=$(printf "\e[0m") \
+    LESS_TERMCAP_so=$(printf "\e[1;44;33m") \
+    LESS_TERMCAP_ue=$(printf "\e[0m") \
+    LESS_TERMCAP_us=$(printf "\e[1;32m") \
+    man "$@"
 }
 if (( $+commands[unbuffered] )); then
-	function less_with_unbuffer() {
-		unbuffered "$@" |& less -SR
-	}
-		alias ul=less_with_unbuffer
+  function less_with_unbuffer() {
+    unbuffered "$@" |& less -SR
+  }
+    alias ul=less_with_unbuffer
 fi
 
 # * »»»» grep
@@ -238,16 +238,16 @@ alias grep='grep --color'
 
 # * »»»» grc
 if (( $+commands[grc] )); then
-	alias mount='grc mount'
-	alias ifconfig='grc ifconfig'
-	alias dig='grc dig'
-	alias ldap='grc ldap'
-	alias netstat='grc netstat'
-	alias ping='grc ping'
-	alias ps='grc ps'
-	alias traceroute='grc traceroute'
-	alias gcc='grc gcc'
-	alias g++='grc g++'
+  alias mount='grc mount'
+  alias ifconfig='grc ifconfig'
+  alias dig='grc dig'
+  alias ldap='grc ldap'
+  alias netstat='grc netstat'
+  alias ping='grc ping'
+  alias ps='grc ps'
+  alias traceroute='grc traceroute'
+  alias gcc='grc gcc'
+  alias g++='grc g++'
 fi
 
 # * ««« --------------------------------/
@@ -262,8 +262,8 @@ fi
 
 
 
-# * »		[2] look
-# -------------------------------------------														/
+# * »   [2] look
+# -------------------------------------------                           /
 # ---------------------------------------------------------------------/
 # [
 
@@ -273,7 +273,7 @@ setopt prompt_subst
 
 
 
-# * »»	theme ------------------------------------------/
+# * »»  theme ------------------------------------------/
 # [[
 
 autoload -U colors; colors
@@ -284,19 +284,19 @@ export TERM=xterm-256color
 
 
 
-# * »»	ls color ---------------------------------------/
+# * »»  ls color ---------------------------------------/
 # [[
 
 export LSCOLORS=gxfxcxdxbxegedabagacad
 export LS_COLORS='no=00;38;5;244:rs=0:di=00;38;5;33:ln=00;38;5;37:mh=00:pi=48;5;230;38;5;136;01:so=48;5;230;38;5;136;01:do=48;5;230;38;5;136;01:bd=48;5;230;38;5;244;01:cd=48;5;230;38;5;244;01:or=48;5;235;38;5;160:su=48;5;160;38;5;230:sg=48;5;136;38;5;230:ca=30;41:tw=48;5;64;38;5;230:ow=48;5;235;38;5;33:st=48;5;33;38;5;230:ex=00;38;5;64:'
 if ! [[ $OSTYPE = msys* ]]; then
-	if [ -e $ZDOTDIR/rc/dircolors ]; then
-		if (( $+commands[dircolors] )); then
-			eval $(dircolors $ZDOTDIR/rc/dircolors)
-		elif (( $+commands[gdircolors] )); then
-			eval $(gdircolors $ZDOTDIR/rc/dircolors)
-		fi
-	fi
+  if [ -e $ZDOTDIR/rc/dircolors ]; then
+    if (( $+commands[dircolors] )); then
+      eval $(dircolors $ZDOTDIR/rc/dircolors)
+    elif (( $+commands[gdircolors] )); then
+      eval $(gdircolors $ZDOTDIR/rc/dircolors)
+    fi
+  fi
 fi
 export ZLS_COLORS=$LS_COLORS
 export CLICOLOR=true
@@ -305,7 +305,7 @@ zstyle ':completion:*:default' list-colors ${(s.:.)LS_COLORS}
 alias ls='ls -F --color=auto --group-directories-first'
 
 function cd() {
-	builtin cd $@ && ls;
+  builtin cd $@ && ls;
 }
 
 # ]]
@@ -313,7 +313,7 @@ function cd() {
 
 
 
-# * »»	prompt -----------------------------------------/
+# * »»  prompt -----------------------------------------/
 # [[
 
 PROMPT="[%~]%(!,#,$) "
@@ -321,40 +321,40 @@ RPROMPT="[%n|%m|%w|%*]"
 SPROMPT="%r is correct [n,y,a,e]: "
 
 if [[ $TERM = xterm* ]];then
-	local DARKGRAY=237
-	local WHITE=15
-	local GREEN=47
-	local BLUE=31
-	local RED=161
+  local DARKGRAY=237
+  local WHITE=15
+  local GREEN=47
+  local BLUE=31
+  local RED=161
 
-	local BACKGROUND=${DARKGRAY}
-	local FOREGROUND=${WHITE}
-	local COLOR="%F{${FOREGROUND}}%K{${BACKGROUND}}"
-	local PROMPTBODY="${COLOR} %~ ${COLOR}%F{${WHITE}}%(?.%K{${BLUE}}.%K{${RED}}) * %f%k "
+  local BACKGROUND=${DARKGRAY}
+  local FOREGROUND=${WHITE}
+  local COLOR="%F{${FOREGROUND}}%K{${BACKGROUND}}"
+  local PROMPTBODY="${COLOR} %~ ${COLOR}%F{${WHITE}}%(?.%K{${BLUE}}.%K{${RED}}) * %f%k "
 
-	case ${UID} in
-		0) #root
-			local UCOLOR=${RED};;
-		*)
-			local UCOLOR=${BLUE};;
-	esac
+  case ${UID} in
+    0) #root
+      local UCOLOR=${RED};;
+    *)
+      local UCOLOR=${BLUE};;
+  esac
 
-	PROMPT=${PROMPTBODY}
-	RPROMPT="%F{${FOREGROUND}}%K{${UCOLOR}} %n %F{${GREEN}}%K{${BACKGROUND}} %m ${COLOR}|${COLOR} %w ${COLOR}|${COLOR} %* %f%k"
+  PROMPT=${PROMPTBODY}
+  RPROMPT="%F{${FOREGROUND}}%K{${UCOLOR}} %n %F{${GREEN}}%K{${BACKGROUND}} %m ${COLOR}|${COLOR} %w ${COLOR}|${COLOR} %* %f%k"
 
-	if (( $+commands[python] )); then
-		if [ -e $ZDOTDIR/rc/plugin/prompt.py ]; then
-			function u_prompt() {
-				local RETURN=$?
-				if [ -e $ZDOTDIR/rc/plugin/prompt.py ]; then
-					PROMPT="$(~/.zsh/rc/plugin/prompt.py ${RETURN})"
-				else
-					PROMPT=${PROMPTBODY}
-				fi
-			}
-			precmd() { u_prompt }
-		fi
-	fi
+  if (( $+commands[python] )); then
+    if [ -e $ZDOTDIR/rc/plugin/prompt.py ]; then
+      function u_prompt() {
+        local RETURN=$?
+        if [ -e $ZDOTDIR/rc/plugin/prompt.py ]; then
+          PROMPT="$(~/.zsh/rc/plugin/prompt.py ${RETURN})"
+        else
+          PROMPT=${PROMPTBODY}
+        fi
+      }
+      precmd() { u_prompt }
+    fi
+  fi
 fi
 
 
@@ -378,39 +378,39 @@ TRAPALRM() { redraw_tmout }
 
 
 
-# * »		[3] os
-# -------------------------------------------														/
+# * »   [3] os
+# -------------------------------------------                           /
 # ---------------------------------------------------------------------/
 # [
 
 case ${OSTYPE} in #uname http://en.wikipedia.org/wiki/Uname
-	# linux
-	linux*)
-		if [ -d ${HOME}/bin ]; then
-			export PATH=${HOME}/bin:${PATH}
-		fi
-		if [ -d ${HOME}/usr/bin ]; then
-			export PATH=${HOME}/usr/bin:${PATH}
-		fi
-		if [ -e ${HOME}/.tmux.conf ]; then 
-			[[ -z "${TMUX}" && -z "${WINDOW}" && ! -z "${PS1}" ]] && tmux
-		fi ;;
-	# mac os
-	darwin*)
-		alias ls='ls -G -F -L'
-		function cd() {
-			builtin cd $@ && ls;
-		} ;;
-	#windows
-	CYGWIN*) ;;
-	msys*)
-		alias shutdown='shutdown -s -f'
-		if (( $+commands[winpty] )); then
-			alias cl='winpty cl'
-			alias diskpart='winpty diskpart'
-			alias sdelete='winpty sdelete'
-			alias mysql='winpty mysql'
-		fi ;;
+  # linux
+  linux*)
+    if [ -d ${HOME}/bin ]; then
+      export PATH=${HOME}/bin:${PATH}
+    fi
+    if [ -d ${HOME}/usr/bin ]; then
+      export PATH=${HOME}/usr/bin:${PATH}
+    fi
+    if [ -e ${HOME}/.tmux.conf ]; then 
+      [[ -z "${TMUX}" && -z "${WINDOW}" && ! -z "${PS1}" ]] && tmux
+    fi ;;
+  # mac os
+  darwin*)
+    alias ls='ls -G -F -L'
+    function cd() {
+      builtin cd $@ && ls;
+    } ;;
+  #windows
+  CYGWIN*) ;;
+  msys*)
+    alias shutdown='shutdown -s -f'
+    if (( $+commands[winpty] )); then
+      alias cl='winpty cl'
+      alias diskpart='winpty diskpart'
+      alias sdelete='winpty sdelete'
+      alias mysql='winpty mysql'
+    fi ;;
 esac
 
 # ]
@@ -419,8 +419,8 @@ esac
 
 
 
-# * »		[4] local setting
-# -------------------------------------------														/
+# * »   [4] local setting
+# -------------------------------------------                           /
 # ---------------------------------------------------------------------/
 # [
 
@@ -429,7 +429,7 @@ export H_FLUG=0
 source_file ${HOME}/.cache/zsh/zsh_local
 
 if [ ${H_FLUG} = 1 ]; then
-	source_file $ZDOTDIR/rc/plugin/syntax/zsh-syntax-highlighting.zsh
+  source_file $ZDOTDIR/rc/plugin/syntax/zsh-syntax-highlighting.zsh
 fi
 
 # ]
